export interface Settings {
  id: string;
  coupleName: string;
  weddingDate: string | null;
  weddingTime: string | null;
  venueName: string;
  venueAddress: string;
  ceremonyType: string;
  dressCode: string;
  contactEmailJoint: string;
  contactEmailBride: string;
  contactEmailGroom: string;
  contactPhoneAshley: string;
  contactPhoneJacob: string;
  contactPhoneMaryLorraine: string;
  contactPhoneMollie: string;
  weddingHashtag: string;
  sitePassword: string;
  sitePasswordEnabled: boolean;
  rsvpDeadline: string | null;
  heroTagline: string;
  heroTaglinePostWedding: string;
  ourStoryContent: string;
  travelContent: string;
  preWeddingContent: string;
  postWeddingContent: string;
  weatherInfo: string;
  parkingInfo: string;
  childrenPolicy: string;
  unpluggedCeremonyNotice: string;
  accessibilityNote: string;
  dressCodeImages: string;
  dressCodePinterestLink: string;
  faqContent: string;
  photoShareLink: string;
  ogImage: string;
  ogDescription: string;
  socialInstagram: string;
  socialFacebook: string;
  socialTikTok: string;
  registryNote: string;
  entertainmentNote: string;
  raffleTicketCount: number;
  rafflePrize: string;
  notifyOnRsvp: boolean;
  notificationEmail: string;
  bannerText: string;
  bannerUrl: string;
  bannerActive: boolean;
  bannerColor: string;
  hideUnconfirmedWeddingParty: boolean;
}
